### ISSUE TITLE
[problem] make checkを実施するとコンパイルエラーが発生する 

### ISSUE THREAD

**Issue by hayashi770** [FairyDevicesRD/tumbler#2]
libtumblerディレクトリで `make check` を実行した際にエラーになってしまいました。

```
＜エラーメッセージ内容＞
buttons_test.cpp: In function ‘int main(int, char**)’:
buttons_test.cpp:75:69: error: invalid conversion from ‘void (*)(std::vector<tumbler::ButtonState>)’ to ‘tumbler::ButtonStateCallback {aka void (*)(std::vector<tumbler::ButtonState>, tumbler::ButtonInfo, void*)}’ [-fpermissive]
     Buttons& buttons = Buttons::getInstance(ButtonStateFunc, nullptr);
```

この対応として、`https://github.com/FairyDevicesRD/tumbler/tree/master/libtumbler/test/buttons_test.cpp` の以下のコード 
`void ButtonStateFunc(std::vector<ButtonState> state)` 
を
`void ButtonStateFunc(std::vector<ButtonState> state, ButtonInfo buttonInfo, void* userdata)` に変更して実行しましたが、問題ないでしょうか？

**Comment by nagisasaka** [comment]
問題ございません、make check の実装が後手に回っていることによる問題となります。実動作に影響はございません。

**Comment by nagisasaka** [comment]
上記 42d3695 にて修正いたしました。ご指摘いただきありがとうございました。

**Comment by hayashi770** [comment]
迅速なご回答、及びご対応ありがとうございました。
